config/routes.rb
Rails.application.routes.draw do
  # resources :products

  resources :order_items
  get 'cart', to: 'cart#show', as: :cart_path
  # get 'categories/:id', to: 'categories#destroy'
  resources :categories
  	# resources :products
  # end
  root 'pages#home'
	get 'menu', to: 'menu#index'
	get 'search', to: 'menu#search'
  devise_for :users
  
  get 'home', to: "pages#home"
  get 'catering', to: 'pages#catering'
  get 'info'  , to: 'pages#info'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController


	before_action :set_cats

  def index
  	@page = 'menu'

  	@products = Product.all
    @order_item = current_order.order_items.new

  end
   def search
   	query = params[:search]
   	results = Product.where('name LIKE ?',"%#{query}%")

   	 if params[:filter] == 'Select Filter'
   	 	@products = results

   	 else
      #Dairy Free -> 'Dairy_Free ->'dairy_free' ->:dairy_free' 
   	 	symbol = params[:filter].gsub(/ /,'_').downcase.to_sym

   	 	#@products = results.where(:dairy_free => true)
   	 	@products =results.where(symbol => true)
   	 end

   end

    private
    def set_cats
    	@cats = Category.all.where(display: true)
  end

end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/menu/_products.html.erb
<div  class = "row" > 
 <% @cats.each do |cat| %>
<%  unless cat.products.where(featured: true).blank? %>
<% if  cat.products.where(featured: true).first.image.attached? %> 
 <%= image_tag(cat.products.where(featured: true).last.image, class:'img-fluid')%> 
 <% end %>
  <% end %>

 <% @products.each do |product| %>
 <% if  product.category == cat %>
 <div  class="col-4">
 	<h5>
 		<%= product.name %>
 	</h5>
 	<p>
 		<%= product.description %>
 	</p>

 	<span><%= product.price %><%= "| Available for catering" if  product.catering %></span>
    <%= form_with model: @order_item do  |f| %>
    <%= f.hidden_field  :product_id, value: product.id  %>
    <%= f.number_field  :quantity, value: 1,min: 1 %>
    <%= f.submit "Add To Cart" %>
    <% end %> 
</div>
 <% end %>
 <% end %>
 <% end %>
  <div class ='col-12'>
 	<h1 style= "text-align:center;"><%= @cats.last(3).first.heading %></h1>
 	<hr />
 </div>
 <div class ='col-12'>
 	<h1 style= "text-align:center;"><%= @cats.last(2).first.heading %></h1>
 	<hr />
 </div>
 <div class ='col-12'>
 	<h1 style= "text-align:center;"><%= @cats.last(1).first.heading %></h1>
 	<hr />
 </div>
</div>

app/views/menu/index.html.erb
<!-- <h1>Menu#index</h1>
<p>Find me in app/views/menu/index.html.erb</p>
 -->


 <div class ="menu-container">
 	<div class = "row" >
 		<div class = "col-12">
 			<%= form_tag(search_path,method: "get",remote: true ) do %>
 			<div class = "input-group mb-5">
 				<div class = "col-8"style= "padding:0" >
 					<%= text_field_tag :search,'',class: "form_control",placeholder: 'search...',onkeydown:"clickSubmit();" %>
 				</div>
 					<div class ='col-3' style="padding:0">
 						<%= select_tag "filter", options_for_select(['Select Filter',
 							'Dairy Free',
 							'Gluten Free',
 						    'Kosher',
 						    'Peanut Free',
 						    'Vegan',
 						    'Vegetarian']), class: 'custom-select', onchange: 'clickSubmit()' %>
 						 </div>
 						
 						<!--  <div class='col-1' style="padding:0"> -->
 						 	<%= submit_tag 'Search', class: 'btn btn-dark',id:'search_submit',style: "display:none"%>
 					 </div>
 				</div>
 				<% end %>
 			</div>
 		<div id ="menu-products-container">
 			<%= render 'menu/products' %>
 		</div>
 	</div>
 			
 			<script>
 				function clickSubmit(){
 					$('search_submit').trigger('click');
 				}
</script>


 

app/views/menu/search.js.erb
$("#menu-products-container").html("<%= j render 'menu/products' %>");