config/routes.rb
Rails.application.routes.draw do
  # resources :products

  resources :order_items
  get 'cart', to: 'cart#show', as: :cart_path
  # get 'categories/:id', to: 'categories#destroy'
  resources :categories
  	# resources :products
  # end
  root 'pages#home'
	get 'menu', to: 'menu#index'
	get 'search', to: 'menu#search'
  devise_for :users
  
  get 'home', to: "pages#home"
  get 'catering', to: 'pages#catering'
  get 'info'  , to: 'pages#info'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_links.html.erb
<div class="col-10">

	<h5 class="link-container">
		<% link_to "Home", home_path, class: "link  #{@page == 'home'   ?  'active'  : ''}" %>
	</h5>
	<h5 class="link-container">
		<%= link_to "Home", home_path, class: "link  #{@page == 'home'   ?  'active'  : ''}" %>
	</h5>
	<h5 class="link-container">
		<%= link_to "Menu", menu_path, class: "link  #{@page == 'menu'   ?  'active'  : ''}" %>
	</h5>
	<h5 class="link-container">
		<%= link_to "Catering", info_path, class: "link  #{@page == 'catering'   ?  'active'  : ''}" %>
	</h5>
	<h5 class="link-container">
		<%= link_to "More info", info_path, class: "link  #{@page == 'info'   ?  'active'  : ''}" %>

	</h5>
	<h5 class="link-container">
		<%= link_to "Customer Reviews", info_path, class: "link  #{@page == 'reviews'   ?  'active'  : ''}" %>
	</h5>
		<h5 class="link-container">
		<%= link_to "Categories", categories_path, class: "link  #{@page == 'categories'   ?  'active'  : ''}" %>
	</h5>


</div>

app/views/layouts/_title.html.erb
<div class = 'title-card'>
	<h1 class='title-text'>
		Frank's Foods 
	</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'src/application', media: 'all'%>
    <%#= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital@1&display=swap" rel="stylesheet">
  </head>
  <body >
     <div class="row <%= class_selector(params) %>">
      <%= render "shared/nav" %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <div class="<%= @page %>-page">
        <div class="col-4 page" style="margin-top: -50px;">
          <%= render'layouts/links' %>
        </div>
        <div class='col-8 container' style="margin-top: -150px;">
          <% unless @page == 'home'%>
          <%= render 'layouts/title' %>
          <% end %>
        <%= yield %>
        </div>
      </div>
   </div>
  </body>
</html>